Use uint64_t instead of u_int64_t
`uintN_t` is standard C99 type available in `<stdint.h>`, whereas `u_intN_t`
is defined `<sys/types.h>`

As upmpdcli already uses the `uintN_t` type, replace the few existing
`u_intN_t` types, as it breaks build with the musl C library, which is
very strict, because of the missing `<sys/types.h>`:

```
src/mediaserver/cdplugins/netfetch.h:71:5: error: ‘u_int64_t’ does not name a type
     u_int64_t datacount() {
```